config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
          end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {})
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # if a user is NOT autenticated. "!" makes it the opposite
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    # @post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    # @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
    end
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "Not authorized to edit this post" if @post.nil?
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Members-only', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <%= render 'devise/shared/login_header' %>
            <% else %>
                <%= render 'devise/shared/logout_header' %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class= "container">
      <p style="color: green"><%= notice %></p>
      <p style="color: red"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<!-- <div>
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <% if user_signed_in? %>
    <p>
      <strong>Author:</strong>
      <%= User.find(post.user_id).username %>
    </p>
    <% else %>
      <p>anonymous</p>
  <% end %>
</div>


 --><div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <% if user_signed_in? %>
        <p>
          <%= User.find(post.user_id).username %>
        </p>
        <% else %>
          <p>anonymous</p>
      <% end %>
    </h6>
    <p class="card-text"><%= post.body %></p>
  </div>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post, class: "btn btn-primary btn-sm" %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path, class: "btn btn-outline-secondary" %>

app/views/posts/new.html.erb
<h1>Create a Post</h1>

<%= form_with model: @post do |form| %>
  <div class="field form-group">
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title,  class: "form-control" %>
  </div>

  <div class = "field form-group">
    <%= form.label :body, "Body:" %>
    <%= form.text_area :body, class: "form-control", size: "60x10" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :post_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class = "actions">
    <%= form.submit  class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to "Back to posts", posts_path, class: "btn btn-light" %>
  <%= button_to "Destroy this post", @post, method: :delete %>
</div>